# Omakase Ruby styling for Rails
inherit_gem: { standard: config/base.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
require:
  - standard

