production:
  video_batch_processing:
    class: VideoBatchProcessingJob
    schedule: every 6 hours

# Example schedule syntax:
#   schedule: every hour
#   schedule: every 6 hours
#   schedule: at 5am every day
#   schedule: every Monday at 9am
