service: almaktabah-frontend
image: mohamedrez/almaktabah-frontend
servers:
  web:
    - 188.245.209.159
registry:
  username: mohamedrez
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  clear:
    NEXT_PUBLIC_API_URL: "https://ilm.hachimy.com/api"
proxy:
  ssl: true
  host: ilm.hachimy.com
