export const books = [
  {
    id: 1,
    title: "السبيل المحني للمسلم من الفتن",
    image: "/placeholder.svg?height=300&width=200",
    pages: 53,
    year: 1437,
    type: "الأولى",
    description: "توضيح في بيان السبيل الذي ينجي من الفتن",
    pdfUrl: "/books/book-1.pdf",
    chapters: [
      { id: 1, title: "مقدمة", pageStart: 1, pageEnd: 3 },
      { id: 2, title: "أسباب الفتن", pageStart: 4, pageEnd: 12 },
      { id: 3, title: "كيفية النجاة من الفتن", pageStart: 13, pageEnd: 25 },
      { id: 4, title: "نماذج من الفتن المعاصرة", pageStart: 26, pageEnd: 40 },
      { id: 5, title: "وصايا للمسلم في زمن الفتن", pageStart: 41, pageEnd: 50 },
      { id: 6, title: "خاتمة", pageStart: 51, pageEnd: 53 },
    ],
  },
  {
    id: 2,
    title: "القول البين الأظهر",
    image: "/placeholder.svg?height=300&width=200",
    pages: 196,
    year: 1437,
    type: "الثانية",
    description: "القول البين الأظهر في الدعوة إلى الله والأمر بالمعروف والنهي عن المنكر",
    pdfUrl: "/books/book-2.pdf",
    chapters: [
      { id: 1, title: "مقدمة", pageStart: 1, pageEnd: 5 },
      { id: 2, title: "فضل الدعوة إلى الله", pageStart: 6, pageEnd: 20 },
      { id: 3, title: "صفات الداعية", pageStart: 21, pageEnd: 45 },
      { id: 4, title: "أساليب الدعوة", pageStart: 46, pageEnd: 80 },
      { id: 5, title: "الأمر بالمعروف والنهي عن المنكر", pageStart: 81, pageEnd: 120 },
      { id: 6, title: "ضوابط الأمر بالمعروف والنهي عن المنكر", pageStart: 121, pageEnd: 150 },
      { id: 7, title: "آداب الأمر بالمعروف والنهي عن المنكر", pageStart: 151, pageEnd: 180 },
      { id: 8, title: "خاتمة", pageStart: 181, pageEnd: 196 },
    ],
  },
  {
    id: 3,
    title: "توضيح البر المنعم بشرح صحيح الإمام مسلم 3",
    image: "/placeholder.svg?height=300&width=200",
    pages: 5111,
    volumes: 9,
    year: 1439,
    type: "الأولى",
    description: "متوسط الحجم، شامل لجميع أحاديث الصحيح بميزة التعقب",
    pdfUrl: "/books/book-3.pdf",
    chapters: [
      { id: 1, title: "مقدمة", pageStart: 1, pageEnd: 20 },
      { id: 2, title: "كتاب الإيمان", pageStart: 21, pageEnd: 300 },
      { id: 3, title: "كتاب الطهارة", pageStart: 301, pageEnd: 600 },
      { id: 4, title: "كتاب الصلاة", pageStart: 601, pageEnd: 1200 },
      { id: 5, title: "كتاب الزكاة", pageStart: 1201, pageEnd: 1500 },
      { id: 6, title: "كتاب الصيام", pageStart: 1501, pageEnd: 1800 },
      { id: 7, title: "كتاب الحج", pageStart: 1801, pageEnd: 2200 },
      { id: 8, title: "كتاب البيوع", pageStart: 2201, pageEnd: 2600 },
      { id: 9, title: "كتاب النكاح", pageStart: 2601, pageEnd: 3000 },
      { id: 10, title: "كتاب الطلاق", pageStart: 3001, pageEnd: 3300 },
      { id: 11, title: "كتاب الجهاد والسير", pageStart: 3301, pageEnd: 3600 },
      { id: 12, title: "كتاب الإمارة", pageStart: 3601, pageEnd: 3900 },
      { id: 13, title: "كتاب الأقضية", pageStart: 3901, pageEnd: 4200 },
      { id: 14, title: "كتاب الأشربة", pageStart: 4201, pageEnd: 4400 },
      { id: 15, title: "كتاب اللباس والزينة", pageStart: 4401, pageEnd: 4600 },
      { id: 16, title: "كتاب الفضائل", pageStart: 4601, pageEnd: 4900 },
      { id: 17, title: "كتاب الفتن وأشراط الساعة", pageStart: 4901, pageEnd: 5111 },
    ],
  },
  {
    id: 4,
    title: "شرح كتاب التوحيد",
    image: "/placeholder.svg?height=300&width=200",
    pages: 320,
    year: 1440,
    type: "الثالثة",
    description: "شرح مفصل لكتاب التوحيد للإمام محمد بن عبد الوهاب",
    pdfUrl: "/books/book-4.pdf",
    chapters: [
      { id: 1, title: "مقدمة", pageStart: 1, pageEnd: 10 },
      { id: 2, title: "فضل التوحيد وما يكفر من الذنوب", pageStart: 11, pageEnd: 25 },
      { id: 3, title: "من حقق التوحيد دخل الجنة بغير حساب", pageStart: 26, pageEnd: 35 },
      { id: 4, title: "الخوف من الشرك", pageStart: 36, pageEnd: 50 },
      { id: 5, title: "الدعاء إلى شهادة أن لا إله إلا الله", pageStart: 51, pageEnd: 65 },
      { id: 6, title: "تفسير التوحيد وشهادة أن لا إله إلا الله", pageStart: 66, pageEnd: 80 },
      { id: 7, title: "من الشرك لبس الحلقة والخيط ونحوهما لرفع البلاء أو دفعه", pageStart: 81, pageEnd: 95 },
      { id: 8, title: "ما جاء في الرقى والتمائم", pageStart: 96, pageEnd: 110 },
      { id: 9, title: "من تبرك بشجر أو حجر ونحوهما", pageStart: 111, pageEnd: 125 },
      { id: 10, title: "ما جاء في الذبح لغير الله", pageStart: 126, pageEnd: 140 },
      { id: 11, title: "لا يذبح لله في مكان يذبح فيه لغير الله", pageStart: 141, pageEnd: 155 },
      { id: 12, title: "من الشرك النذر لغير الله", pageStart: 156, pageEnd: 170 },
      { id: 13, title: "من الشرك الاستعاذة بغير الله", pageStart: 171, pageEnd: 185 },
      { id: 14, title: "من الشرك أن يستغيث بغير الله أو يدعو غيره", pageStart: 186, pageEnd: 200 },
      { id: 15, title: "قول الله تعالى: {أَيُشْرِكُونَ مَا لَا يَخْلُقُ شَيْئًا}", pageStart: 201, pageEnd: 215 },
      { id: 16, title: "قول الله تعالى: {حَتَّى إِذَا فُزِّعَ عَن قُلُوبِهِمْ}", pageStart: 216, pageEnd: 230 },
      { id: 17, title: "الشفاعة", pageStart: 231, pageEnd: 245 },
      { id: 18, title: "قول الله تعالى: {إِنَّكَ لَا تَهْدِي مَنْ أَحْبَبْتَ}", pageStart: 246, pageEnd: 260 },
      { id: 19, title: "ما جاء أن سبب كفر بني آدم وتركهم دينهم هو الغلو في الصالحين", pageStart: 261, pageEnd: 275 },
      { id: 20, title: "ما جاء في حماية المصطفى صلى الله عليه وسلم جناب التوحيد", pageStart: 276, pageEnd: 290 },
      { id: 21, title: "خاتمة", pageStart: 291, pageEnd: 320 },
    ],
  },
]
