import type { Lesson, Fatwa } from "@/types"

export const lessons: Lesson[] = [
  {
    id: 1,
    title: "العقيدة الطحاوية 1 من بداية الكتاب - إلى قوله وَلا شَيْءَ مِثْلُهُ",
    date: "2018/03/13",
    type: "دروس علمية",
    category: "العقيدة",
    duration: 45,
    audioUrl: "/audio/lesson-1.mp3",
    description:
      "البداية الربانية في شرح العقيدة الطحاوية عقيدة أهل السنة والجماعة بسم الله الرحمن الرحيم الحمد لله رب العالمين، والصلاة والسلام على أشرف الأنبياء والمرسلين، نبينا محمد وعلى آله وصحبه أجمعين.",
    thumbnailUrl: "/placeholder.svg?height=200&width=400",
    seriesId: 1,
    seriesName: "شرح العقيدة الطحاوية",
    seriesOrder: 1,
    totalInSeries: 12,
  },
  {
    id: 2,
    title: "العقيدة الطحاوية 2 - من قوله وَلا شَيْءَ مِثْلُهُ إلى قوله وَلا يَحْمِلُهُ العَرْشُ",
    date: "2018/03/20",
    type: "دروس علمية",
    category: "العقيدة",
    duration: 48,
    audioUrl: "/audio/lesson-2.mp3",
    description: "استكمال شرح العقيدة الطحاوية من قوله وَلا شَيْءَ مِثْلُهُ إلى قوله وَلا يَحْمِلُهُ العَرْشُ، وبيان صفات الله تعالى.",
    thumbnailUrl: "/placeholder.svg?height=200&width=400",
    seriesId: 1,
    seriesName: "شرح العقيدة الطحاوية",
    seriesOrder: 2,
    totalInSeries: 12,
  },
  {
    id: 3,
    title: "كتاب الحج - حل العقدة في شرح العمدة -7",
    date: "2023/05/20",
    type: "دروس علمية",
    category: "الفقه",
    duration: 52,
    audioUrl: "/audio/lesson-3.mp3",
    description: "شرح مفصل لكتاب الحج من كتاب العمدة، يتناول أحكام الحج والعمرة وشروطهما وأركانهما وواجباتهما.",
    thumbnailUrl: "/placeholder.svg?height=200&width=400",
    seriesId: 2,
    seriesName: "حل العقدة في شرح العمدة",
    seriesOrder: 7,
    totalInSeries: 15,
  },
  {
    id: 4,
    title: "كتاب الحج - حل العقدة في شرح العمدة -8",
    date: "2023/06/15",
    type: "دروس علمية",
    category: "الفقه",
    duration: 55,
    audioUrl: "/audio/lesson-4.mp3",
    description: "استكمال شرح كتاب الحج من كتاب العمدة، يتناول محظورات الإحرام وأحكام الفدية.",
    thumbnailUrl: "/placeholder.svg?height=200&width=400",
    seriesId: 2,
    seriesName: "حل العقدة في شرح العمدة",
    seriesOrder: 8,
    totalInSeries: 15,
  },
  {
    id: 5,
    title: "كتاب الحج - حل العقدة في شرح العمدة -9",
    date: "2023/07/10",
    type: "دروس علمية",
    category: "الفقه",
    duration: 50,
    audioUrl: "/audio/lesson-5.mp3",
    description: "استكمال شرح كتاب الحج من كتاب العمدة، يتناول صفة الحج والعمرة وأعمال يوم التروية ويوم عرفة.",
    thumbnailUrl: "/placeholder.svg?height=200&width=400",
    seriesId: 2,
    seriesName: "حل العقدة في شرح العمدة",
    seriesOrder: 9,
    totalInSeries: 15,
  },
  {
    id: 6,
    title: "كتاب الحج - حل العقدة في شرح العمدة -10",
    date: "2023/08/05",
    type: "دروس علمية",
    category: "الفقه",
    duration: 53,
    audioUrl: "/audio/lesson-6.mp3",
    description: "استكمال شرح كتاب الحج من كتاب العمدة، يتناول أعمال يوم النحر وأيام التشريق والهدي والأضحية.",
    thumbnailUrl: "/placeholder.svg?height=200&width=400",
    seriesId: 2,
    seriesName: "حل العقدة في شرح العمدة",
    seriesOrder: 10,
    totalInSeries: 15,
  },
  {
    id: 7,
    title: "شرح أصول السنة للإمام أحمد بن حنبل - الدرس الأول",
    date: "2022/11/15",
    type: "دروس علمية",
    category: "العقيدة",
    duration: 47,
    audioUrl: "/audio/lesson-7.mp3",
    description:
      "شرح مفصل لكتاب أصول السنة للإمام أحمد بن حنبل، يتناول أصول العقيدة الصحيحة وأهمية التمسك بالكتاب والسنة.",
    thumbnailUrl: "/placeholder.svg?height=200&width=400",
    seriesId: 3,
    seriesName: "شرح أصول السنة للإمام أحمد بن حنبل",
    seriesOrder: 1,
    totalInSeries: 8,
  },
  {
    id: 8,
    title: "شرح أصول السنة للإمام أحمد بن حنبل - الدرس الثاني",
    date: "2022/11/22",
    type: "دروس علمية",
    category: "العقيدة",
    duration: 49,
    audioUrl: "/audio/lesson-8.mp3",
    description: "استكمال شرح كتاب أصول السنة للإمام أحمد بن حنبل، يتناول مسائل الإيمان والقدر.",
    thumbnailUrl: "/placeholder.svg?height=200&width=400",
    seriesId: 3,
    seriesName: "شرح أصول السنة للإمام أحمد بن حنبل",
    seriesOrder: 2,
    totalInSeries: 8,
  },
]

export const fatwas: Fatwa[] = [
  {
    id: 1,
    title: "حكمة خلق الله الكافر مع علمه سبحانه أنه من أهل النار",
    date: "2023/02/10",
    category: "العقيدة",
    question: "ما حكمة خلق الله الكافر مع علمه سبحانه أنه من أهل النار؟",
    answer:
      "الحمد لله رب العالمين. إن الله تعالى له الحكمة البالغة في كل ما يخلق ويأمر، وقد خلق الله الخلق لعبادته كما قال تعالى: {وَمَا خَلَقْتُ الْجِنَّ وَالْإِنسَ إِلَّا لِيَعْبُدُونِ}. وخلق الله الكافر مع علمه سبحانه أنه من أهل النار له حكم عديدة منها: إظهار قدرة الله تعالى وعدله وحكمته، وابتلاء المؤمنين واختبارهم، وإظهار فضل الإيمان والطاعة، وتحقيق التكليف والاختيار للإنسان. والله أعلم.",
    audioUrl: "/audio/fatwa-1.mp3",
    duration: 8,
    relatedFatwas: [3, 5],
  },
  {
    id: 2,
    title: 'ماذا علي من قال " علي الحرام أن أفعل كذا "',
    date: "2023/01/25",
    category: "الفقه",
    question: 'ماذا علي من قال " علي الحرام أن أفعل كذا " ثم فعله؟',
    answer:
      'الحمد لله رب العالمين. قول القائل "علي الحرام" أو "الحرام يلزمني" ونحو ذلك من الألفاظ، هذا يمين مكفرة عند جمهور أهل العلم، فيجب على من قال ذلك ثم فعل ما حلف على تركه أن يكفر كفارة يمين، وهي إطعام عشرة مساكين، أو كسوتهم، أو تحرير رقبة، فمن لم يجد فصيام ثلاثة أيام. والله أعلم.',
    audioUrl: "/audio/fatwa-2.mp3",
    duration: 6,
    relatedFatwas: [4, 6],
  },
  {
    id: 3,
    title: "اقتصاص الكافر يوم القيامة من المسلم الذي ظلمه",
    date: "2023/03/05",
    category: "العقيدة",
    question: "هل يقتص الكافر يوم القيامة من المسلم الذي ظلمه في الدنيا؟",
    answer:
      "الحمد لله رب العالمين. نعم، يقتص الكافر يوم القيامة من المسلم الذي ظلمه في الدنيا، لأن الله تعالى عدل لا يظلم أحداً، وقد قال النبي صلى الله عليه وسلم: «لتؤدن الحقوق إلى أهلها يوم القيامة، حتى يقاد للشاة الجلحاء من الشاة القرناء». فالظلم محرم مطلقاً سواء كان المظلوم مسلماً أو كافراً. لكن هذا لا يعني أن الكافر سيدخل الجنة بسبب هذا القصاص، بل سيأخذ حقه ثم يكون مصيره إلى النار بسبب كفره. والله أعلم.",
    audioUrl: "/audio/fatwa-3.mp3",
    duration: 7,
    relatedFatwas: [1, 5],
  },
  {
    id: 4,
    title: "هل يمكن غسل الجمعة عن الوضوء",
    date: "2023/03/20",
    category: "الفقه",
    question: "هل يمكن غسل الجمعة عن الوضوء؟",
    answer:
      "الحمد لله رب العالمين. نعم، يجزئ غسل الجمعة عن الوضوء، لأن الغسل أكبر من الوضوء ويشمله، فمن اغتسل فقد توضأ، وهذا باتفاق الأئمة الأربعة. لكن يستحب أن يتوضأ قبل الغسل، لأن النبي صلى الله عليه وسلم كان يفعل ذلك. والله أعلم.",
    audioUrl: "/audio/fatwa-4.mp3",
    duration: 5,
    relatedFatwas: [2, 6],
  },
  {
    id: 5,
    title: "حكم دفع الزكاة لشراء سيارة",
    date: "2023/04/15",
    category: "الفقه",
    question: "ما حكم دفع الزكاة لشراء سيارة لمحتاج يستخدمها في عمله؟",
    answer:
      "الحمد لله رب العالمين. يجوز دفع الزكاة لشراء سيارة لمحتاج يستخدمها في عمله إذا كان محتاجاً إليها لكسب رزقه، وكان من أهل الزكاة كالفقراء والمساكين، لأن هذا من تمام إغنائهم وإعانتهم على الكسب الحلال. وقد نص أهل العلم على جواز إعطاء الفقير من الزكاة ما يشتري به آلة حرفته التي يحتاجها لكسب رزقه. والله أعلم.",
    audioUrl: "/audio/fatwa-5.mp3",
    duration: 6,
    relatedFatwas: [1, 3],
  },
  {
    id: 6,
    title: "حكم الصلاة خلف إمام يرتكب بعض المعاصي",
    date: "2023/05/05",
    category: "الفقه",
    question: "ما حكم الصلاة خلف إمام يرتكب بعض المعاصي؟",
    answer:
      "الحمد لله رب العالمين. تصح الصلاة خلف الإمام الذي يرتكب بعض المعاصي التي لا تصل إلى حد الكفر، وهذا مذهب جمهور أهل العلم، لأن النبي صلى الله عليه وسلم قال: «صلوا خلف كل بر وفاجر». لكن إذا أمكن الصلاة خلف إمام أصلح وأتقى فهو أولى وأفضل. أما إذا كانت المعصية مكفرة فلا تصح الصلاة خلفه. والله أعلم.",
    audioUrl: "/audio/fatwa-6.mp3",
    duration: 7,
    relatedFatwas: [2, 4],
  },
  {
    id: 7,
    title: "حكم قراءة القرآن للحائض",
    date: "2023/06/10",
    category: "الفقه",
    question: "هل يجوز للمرأة الحائض قراءة القرآن؟",
    answer:
      "الحمد لله رب العالمين. الراجح من أقوال أهل العلم أنه يجوز للمرأة الحائض قراءة القرآن من غير مس للمصحف، وهذا قول الإمام مالك والإمام الشافعي في أحد قوليه واختيار شيخ الإسلام ابن تيمية، لعدم وجود دليل صحيح صريح يمنع الحائض من قراءة القرآن. أما مس المصحف فلا يجوز للحائض على الراجح من أقوال أهل العلم. والله أعلم.",
    audioUrl: "/audio/fatwa-7.mp3",
    duration: 6,
    relatedFatwas: [4, 6],
  },
  {
    id: 8,
    title: "حكم التأمين الصحي",
    date: "2023/07/20",
    category: "المعاملات",
    question: "ما حكم التأمين الصحي؟",
    answer:
      "الحمد لله رب العالمين. اختلف العلماء المعاصرون في حكم التأمين الصحي: فمنهم من حرمه مطلقاً لما فيه من الغرر والجهالة والربا. ومنهم من أجازه مطلقاً لأنه من باب التعاون على البر والتقوى. ومنهم من فصّل فأجاز التأمين الصحي التعاوني الذي تقوم به الدولة أو المؤسسات غير الربحية، وحرم التأمين الصحي التجاري الذي تقوم به شركات التأمين التجارية. والراجح - والله أعلم - جواز التأمين الصحي التعاوني، وأما التأمين الصحي التجاري فالأحوط تجنبه لما فيه من المحاذير الشرعية. والله أعلم.",
    audioUrl: "/audio/fatwa-8.mp3",
    duration: 9,
    relatedFatwas: [5, 6],
  },
]

export const books = [
  {
    id: 1,
    title: "السبيل المحني للمسلم من الفتن",
    image: "/placeholder.svg?height=300&width=200",
    pages: 53,
    year: 1437,
    type: "الأولى",
    description: "توضيح في بيان السبيل الذي ينجي من الفتن",
    pdfUrl: "/books/book-1.pdf",
    chapters: [
      { id: 1, title: "مقدمة", pageStart: 1, pageEnd: 3 },
      { id: 2, title: "أسباب الفتن", pageStart: 4, pageEnd: 12 },
      { id: 3, title: "كيفية النجاة من الفتن", pageStart: 13, pageEnd: 25 },
      { id: 4, title: "نماذج من الفتن المعاصرة", pageStart: 26, pageEnd: 40 },
      { id: 5, title: "وصايا للمسلم في زمن الفتن", pageStart: 41, pageEnd: 50 },
      { id: 6, title: "خاتمة", pageStart: 51, pageEnd: 53 },
    ],
  },
  {
    id: 2,
    title: "القول البين الأظهر",
    image: "/placeholder.svg?height=300&width=200",
    pages: 196,
    year: 1437,
    type: "الثانية",
    description: "القول البين الأظهر في الدعوة إلى الله والأمر بالمعروف والنهي عن المنكر",
    pdfUrl: "/books/book-2.pdf",
    chapters: [
      { id: 1, title: "مقدمة", pageStart: 1, pageEnd: 5 },
      { id: 2, title: "فضل الدعوة إلى الله", pageStart: 6, pageEnd: 20 },
      { id: 3, title: "صفات الداعية", pageStart: 21, pageEnd: 45 },
      { id: 4, title: "أساليب الدعوة", pageStart: 46, pageEnd: 80 },
      { id: 5, title: "الأمر بالمعروف والنهي عن المنكر", pageStart: 81, pageEnd: 120 },
      { id: 6, title: "ضوابط الأمر بالمعروف والنهي عن المنكر", pageStart: 121, pageEnd: 150 },
      { id: 7, title: "آداب الأمر بالمعروف والنهي عن المنكر", pageStart: 151, pageEnd: 180 },
      { id: 8, title: "خاتمة", pageStart: 181, pageEnd: 196 },
    ],
  },
  {
    id: 3,
    title: "توضيح البر المنعم بشرح صحيح الإمام مسلم 3",
    image: "/placeholder.svg?height=300&width=200",
    pages: 5111,
    volumes: 9,
    year: 1439,
    type: "الأولى",
    description: "متوسط الحجم، شامل لجميع أحاديث الصحيح بميزة التعقب",
    pdfUrl: "/books/book-3.pdf",
    chapters: [
      { id: 1, title: "مقدمة", pageStart: 1, pageEnd: 20 },
      { id: 2, title: "كتاب الإيمان", pageStart: 21, pageEnd: 300 },
      { id: 3, title: "كتاب الطهارة", pageStart: 301, pageEnd: 600 },
      { id: 4, title: "كتاب الصلاة", pageStart: 601, pageEnd: 1200 },
      { id: 5, title: "كتاب الزكاة", pageStart: 1201, pageEnd: 1500 },
      { id: 6, title: "كتاب الصيام", pageStart: 1501, pageEnd: 1800 },
      { id: 7, title: "كتاب الحج", pageStart: 1801, pageEnd: 2200 },
      { id: 8, title: "كتاب البيوع", pageStart: 2201, pageEnd: 2600 },
      { id: 9, title: "كتاب النكاح", pageStart: 2601, pageEnd: 3000 },
      { id: 10, title: "كتاب الطلاق", pageStart: 3001, pageEnd: 3300 },
      { id: 11, title: "كتاب الجهاد والسير", pageStart: 3301, pageEnd: 3600 },
      { id: 12, title: "كتاب الإمارة", pageStart: 3601, pageEnd: 3900 },
      { id: 13, title: "كتاب الأقضية", pageStart: 3901, pageEnd: 4200 },
      { id: 14, title: "كتاب الأشربة", pageStart: 4201, pageEnd: 4400 },
      { id: 15, title: "كتاب اللباس والزينة", pageStart: 4401, pageEnd: 4600 },
      { id: 16, title: "كتاب الفضائل", pageStart: 4601, pageEnd: 4900 },
      { id: 17, title: "كتاب الفتن وأشراط الساعة", pageStart: 4901, pageEnd: 5111 },
    ],
  },
  {
    id: 4,
    title: "شرح كتاب التوحيد",
    image: "/placeholder.svg?height=300&width=200",
    pages: 320,
    year: 1440,
    type: "الثالثة",
    description: "شرح مفصل لكتاب التوحيد للإمام محمد بن عبد الوهاب",
    pdfUrl: "/books/book-4.pdf",
    chapters: [
      { id: 1, title: "مقدمة", pageStart: 1, pageEnd: 10 },
      { id: 2, title: "فضل التوحيد وما يكفر من الذنوب", pageStart: 11, pageEnd: 25 },
      { id: 3, title: "من حقق التوحيد دخل الجنة بغير حساب", pageStart: 26, pageEnd: 35 },
      { id: 4, title: "الخوف من الشرك", pageStart: 36, pageEnd: 50 },
      { id: 5, title: "الدعاء إلى شهادة أن لا إله إلا الله", pageStart: 51, pageEnd: 65 },
      { id: 6, title: "تفسير التوحيد وشهادة أن لا إله إلا الله", pageStart: 66, pageEnd: 80 },
      { id: 7, title: "من الشرك لبس الحلقة والخيط ونحوهما لرفع البلاء أو دفعه", pageStart: 81, pageEnd: 95 },
      { id: 8, title: "ما جاء في الرقى والتمائم", pageStart: 96, pageEnd: 110 },
      { id: 9, title: "من تبرك بشجر أو حجر ونحوهما", pageStart: 111, pageEnd: 125 },
      { id: 10, title: "ما جاء في الذبح لغير الله", pageStart: 126, pageEnd: 140 },
      { id: 11, title: "لا يذبح لله في مكان يذبح فيه لغير الله", pageStart: 141, pageEnd: 155 },
      { id: 12, title: "من الشرك النذر لغير الله", pageStart: 156, pageEnd: 170 },
      { id: 13, title: "من الشرك الاستعاذة بغير الله", pageStart: 171, pageEnd: 185 },
      { id: 14, title: "من الشرك أن يستغيث بغير الله أو يدعو غيره", pageStart: 186, pageEnd: 200 },
      { id: 15, title: "قول الله تعالى: {أَيُشْرِكُونَ مَا لَا يَخْلُقُ شَيْئًا}", pageStart: 201, pageEnd: 215 },
      { id: 16, title: "قول الله تعالى: {حَتَّى إِذَا فُزِّعَ عَن قُلُوبِهِمْ}", pageStart: 216, pageEnd: 230 },
      { id: 17, title: "الشفاعة", pageStart: 231, pageEnd: 245 },
      { id: 18, title: "قول الله تعالى: {إِنَّكَ لَا تَهْدِي مَنْ أَحْبَبْتَ}", pageStart: 246, pageEnd: 260 },
      { id: 19, title: "ما جاء أن سبب كفر بني آدم وتركهم دينهم هو الغلو في الصالحين", pageStart: 261, pageEnd: 275 },
      { id: 20, title: "ما جاء في حماية المصطفى صلى الله عليه وسلم جناب التوحيد", pageStart: 276, pageEnd: 290 },
      { id: 21, title: "خاتمة", pageStart: 291, pageEnd: 320 },
    ],
  },
]
